---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.height = 16,
  fig.width = 12,
  comment = "#>"
)
library(dplyr)
library(readr)
library(scales)
library(purrr)
library(stringr)
library(ggplot2)
library(showtext)
library(patchwork)
library(forcats)

font_add_google("Schoolbell", "bell")
showtext_auto()
theme_set(theme_light(base_size = 20, base_family = "bell"))

heute <- gsub("-", "", Sys.Date())

source("R/download_current.R")
download_current()


# get recent files
recent_files <- list.files("data_raw", full.names = TRUE) %>% 
  as_tibble() %>% 
  arrange(desc(value)) %>%  
  mutate(cat = basename(value), 
         cat = str_remove(cat, "[0-9]{8}_"),
         cat = str_remove(cat, ".tsv")) %>% 
  slice(1:3)

df <- map(pull(recent_files, value), read_tsv) 
names(df) <- pull(recent_files, cat)

top_views_per_week <- df$weeks_global %>% 
  group_by(show_title) %>% 
  mutate(total_hours = sum(weekly_hours_viewed),
         avg_per_week = total_hours/max(cumulative_weeks_in_top_10)) %>% 
  ungroup() %>% 
  mutate(season_title = ifelse(season_title == "N/A", show_title, season_title),
         category = ifelse(grepl("TV", category), "TV", category),
         category = ifelse(grepl("Film", category), "Movie", category)) %>% 
  group_by(category) %>% 
  arrange(desc(avg_per_week)) %>% 
  select(category, show_title, avg_per_week) %>% 
  distinct()
  


saveRDS(top_views_per_week %>% ungroup(),
     file = paste0("data/", heute, "_top_weeks.rds"))

```

# netflix_top10

<!-- badges: start -->
<!-- badges: end -->

The goal of netflix_top10 is to explore the top 10 netflix shows/movies on regularily bases.

```{r}
top_weeks_n <- 6
data <- df$weeks_global %>% 
  mutate(season_title = ifelse(season_title == "N/A", show_title, season_title),
         category = ifelse(grepl("TV", category), "TV", category),
         category = ifelse(grepl("Film", category), "Movie", category)) %>% 
  filter(show_title %in% pull(slice(top_views_per_week, 1:top_weeks_n), show_title))
  
make_graph <- function(data, cat) {
  
  
  if (cat == "TV") {
    recent_season <- data %>%
      filter(category == cat) %>%
      group_by(show_title) %>%
      arrange(desc(season_title)) %>%
      slice(1) %>%
      pull(season_title)
  } else {
    recent_season <- data %>% 
      filter(category == "Movie") %>%
      distinct(season_title) %>% 
      pull()
  }
  
    data %>% 
    filter(season_title %in% recent_season) %>% 
    ggplot() +
    geom_line(
      aes(
        cumulative_weeks_in_top_10,
        weekly_hours_viewed,
        color = season_title,
        group = season_title
      ),
      size = 1.2,
      alpha = 0.9
    ) +
    geom_point(
      aes(
        cumulative_weeks_in_top_10,
        weekly_hours_viewed,
        color = season_title,
        group = season_title
      ),
      size = 1.2,
      alpha = 0.9
    ) +
    labs(
      title = paste("Top", top_weeks_n, "in", cat),
      subtitle = paste("Date:", format(Sys.Date(), "%b %d, %Y")),
      x = "Cumulative weeks in top 10",
      y = "Weekly hours viewed",
      color = "Title"
    ) +
    #facet_wrap( ~ category, ncol = 1) +
    scale_color_brewer(type = "qual", palette = "Paired") +
    scale_y_continuous(labels = scales::number_format()) +
    scale_x_continuous(labels = scales::number_format(accuracy = 1)) +
    theme(legend.position = "bottom",
          strip.background = element_rect(fill = "#33367C")) +
    guides(colour = guide_legend(title.position = "top", nrow = 2, byrow = TRUE))
  
}



make_graph(data, unique(data$category)[2]) / make_graph(data, unique(data$category)[1])
```


# Combining with imDB

```{r fig.height = 6}
episodes <- vroom::vroom("https://datasets.imdbws.com/title.episode.tsv.gz", delim = "\t")
title <- vroom::vroom("https://datasets.imdbws.com/title.basics.tsv.gz", delim = "\t")
ratings <- vroom::vroom("https://datasets.imdbws.com/title.ratings.tsv.gz", delim = "\t")

netflix_imdb <- title %>% 
  filter(primaryTitle %in% unique(top_views_per_week$show_title))

netflix_shows <- title %>% 
  filter(primaryTitle %in% (top_views_per_week %>% filter(category == "TV") %>% pull(show_title)))
netflix_movies <- title %>% 
  filter(primaryTitle %in% (top_views_per_week %>% filter(category == "Movie") %>% pull(show_title)))

movie_ratings <- netflix_movies %>%
  arrange(primaryTitle) %>% 
  filter(titleType == "movie") %>% 
  select(tconst, primaryTitle, startYear, genres) %>% 
  mutate(startYear = as.numeric(startYear)) %>% 
  group_by(primaryTitle) %>% 
  filter(startYear == max(startYear)) %>% 
  left_join(
    ratings
  ) %>% 
  left_join(
    df$weeks_global %>% 
      group_by(show_title) %>% 
      summarise(total_hours = sum(weekly_hours_viewed),
                total_weeks = max(cumulative_weeks_in_top_10)) %>% 
      rename(primaryTitle = show_title)
  )

movie_ratings %>% 
  ggplot(aes(averageRating, total_hours, label = primaryTitle)) +
  geom_point() +
  ggrepel::geom_text_repel() +
  #theme_light() +
  scale_y_continuous(labels = scales::number_format()) +
  scale_color_viridis_c(guide = "none") +
  scale_size_continuous(guide = "none") +
  labs(x = "Average Movie Rating (Source @imbd)",
       y = "Total Hours Watched (Source @netflix)",
       title = "Movies - Netflix time watched vs IMDB Ration",
       subtitle = paste0(format(Sys.Date(), "%b %d, %Y")))


#### shows
show_ratings <- netflix_shows %>% 
  arrange(primaryTitle) %>%
  filter(titleType == "tvSeries" |
           titleType == "tvMiniSeries") %>% 
  select(tconst, primaryTitle, startYear, genres) %>% 
  mutate(startYear = as.numeric(startYear)) %>% 
  group_by(primaryTitle) %>% 
  filter(startYear == max(startYear, na.rm = TRUE)) %>% 
  ungroup() %>% 
  left_join(
    episodes %>% 
      rename(tconst = parentTconst, tconst_epi = tconst)
  ) %>% 
  left_join(
    ratings %>% 
      rename(tconst_epi = tconst)
  ) %>% 
  left_join(
    df$weeks_global %>% 
      group_by(show_title) %>% 
      summarise(total_hours = sum(weekly_hours_viewed),
                total_weeks = max(cumulative_weeks_in_top_10)) %>% 
      rename(primaryTitle = show_title)
  )

show_ratings %>% 
  mutate(seasonNumber = as.numeric(seasonNumber)) %>% 
  filter(!is.na(numVotes)) %>% 
  group_by(primaryTitle) %>% 
  filter(seasonNumber == max(seasonNumber)) %>% 
  ungroup() %>% 
  group_by(primaryTitle, total_hours) %>% 
  summarise(avg_rating = mean(averageRating, na.rm = TRUE),
            episodes = n()) %>% 
  filter(primaryTitle != "Boruto: Naruto Next Generations") %>% 
  ggplot(aes(avg_rating, total_hours, label = primaryTitle)) +
  geom_point(aes(size = episodes +0.5)) +
  geom_point(aes(size = episodes, color = episodes)) +
  ggrepel::geom_text_repel() +
  #theme_light() +
  scale_y_continuous(labels = scales::number_format()) +
  scale_color_viridis_c(guide = "none") +
  scale_size_continuous(guide = "none") +
  labs(x = "Average Show Rating (Source @imdb)",
       y = "Total Hours Watched of current Season (Source @netflix)",
       title = "TV Shows - Netflix time watched vs IMDB Ration",
       subtitle = paste0(format(Sys.Date(), "%b %d, %Y")))
    

top10_shows <- top_views_per_week %>% 
  slice(1:10) %>% 
  mutate(rank = 1:n()) %>% 
  filter(category == "TV") %>% 
  mutate(show_title = as.factor(show_title),
         show_title = fct_reorder(show_title, rank)) %>% 
  pull(show_title)

top_show_ids <- show_ratings %>%
  filter(primaryTitle %in% top10_shows) %>% 
  distinct(tconst, top10_shows = primaryTitle) %>% 
  left_join(
    tibble(top10_shows) %>% 
      mutate(rank = 1:n())
  ) %>% 
  arrange(rank) %>% 
  pull(tconst)
```


# Insprection of Perfromance of Top Shows on Netflix

```{r fig.height=12}
create_data <- function(id){
  
  #id  <- top_show_ids[1]
  
  data <- episodes %>%
    filter(parentTconst == id) %>%
    left_join(
      ratings
      
    ) %>%
    type_convert() %>%
    filter(!is.na(averageRating)) %>% 
    left_join(
      title %>% 
        filter(tconst == id) %>% 
        count(tconst, primaryTitle, startYear, sort = TRUE) %>% 
        slice(1) %>% 
        select(parentTconst = tconst, primaryTitle, startYear)
    ) %>% 
    mutate(startYear = as.numeric(startYear))
  return(data)
}

create_plot <- function(data, rank = rank) {
  
  #data <- test
  
  min_rate <- data$averageRating %>% min()
  max_rate <- data$averageRating %>% max()
  rating_mid <- max_rate - ((max_rate - min_rate) / 2)
  
  empty_tiles <- tibble(
    episodeNumber = 0:max(data$episodeNumber),
    seasonNumber = 0,
    averageRating = 0:max(data$episodeNumber),
    color = "#000000"
  ) %>%
    bind_rows(
      tibble(
        seasonNumber = 1:max(data$seasonNumber),
        episodeNumber = 0,
        averageRating = 1:max(data$seasonNumber),
        color = "#000000"
      )
    ) %>%
    mutate(label_color = "white")
  
  tile_color <- tibble(
    rating = 0:10,
    color = c(
      "#000000",
      "#a50026",
      "#d73027",
      "#f46d43",
      "#fdae61",
      "#fee08b",
      "#d9ef8b",
      "#a6d96a",
      "#66bd63",
      "#1a9850",
      "#006837"
    )
  )
  
  plot_data <- data %>%
    select(seasonNumber, episodeNumber, averageRating, startYear, title = primaryTitle) %>%
    mutate(rating = floor(averageRating)) %>%
    left_join(tile_color) %>%
    mutate(label_color = "black") %>%
    bind_rows(empty_tiles) #%>% 
  # group_by(seasonNumber) %>% 
  # mutate(first_release = min(startYear, na.rm = TRUE)) %>% 
  # ungroup() %>% 
  # mutate(seasonNumber = ifelse(episodeNumber == 0, paste(seasonNumber, " - ", first_release), seasonNumber)) 
  
  g1 <- plot_data %>%
    ggplot(aes(seasonNumber, episodeNumber, fill = color, label = averageRating)) +
    geom_tile(color = "white") +
    scale_fill_identity(guide = "legend",
                        labels = c(10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)) +
    scale_x_continuous(position = "top") +
    scale_y_reverse() +
    geom_text(aes(color = label_color)) +
    scale_color_manual(values = c("black", "white"), guide = "none") +
    coord_fixed(ratio = 1) +
    labs(x = "Season",
         y = "Episode",
         fill = "Average Rating") +
    theme(line = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank(),
          legend.position = "bottom")
  
  g2 <- plot_data %>% 
    filter(seasonNumber != 0,
           episodeNumber != 0) %>% 
    group_by(seasonNumber) %>%
    mutate(first_release = min(startYear, na.rm = TRUE),
           season_avg_rating = mean(averageRating, na.rm = TRUE),
           season_avg_rating = round(season_avg_rating, 1)) %>%
    ungroup() %>% 
    mutate(season_label = paste("Season", seasonNumber, "-", first_release, " ( avg Rating: ", season_avg_rating, ")")) %>% 
    ggplot(aes(episodeNumber, averageRating, fill = color)) +
    geom_col() +
    facet_wrap(~season_label, ncol = 1) +
    scale_fill_identity(guide = "legend",
                        labels = c(10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)) +
    #theme_light() +
    theme(
      legend.position = "bottom",
      strip.background =element_rect(fill = "#003d80"),
      strip.text = element_text(colour = 'white', face = "bold")) +
    labs(
         x = "Number of Episode",
         y = "Average Rating",
         fill = "") +
    lims(y = c(0, 10))
  
  
  g <- g1 + g2 + 
    plot_annotation(title = paste0("Ratings for: Rank ", rank, " - ", unique(plot_data$title)),
                    caption = paste0("Data Source: @imdb, Date: ", format(Sys.Date(), "%b %d, %Y")))
  return(g)
  
}

all_graphs <- map2(top_show_ids, c(1:10), function(x, y) create_data(x) %>% create_plot(data = ., rank = y))
for (i in seq_along(all_graphs)) {
  print(all_graphs[[i]])
}
```
